# Numpy practice session

In [1]:
import numpy as np


## Creating an array using numpy
- In numpy we can only use one type of data

In [2]:
import numpy as np
food=np.array(["Pakora","Samosa","Raita","Biryani"])
food

array(['Pakora', 'Samosa', 'Raita', 'Biryani'], dtype='<U7')

In [3]:
price=np.array([5,5,5,5])
price


array([5, 5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(price)

4

In [8]:
len(food)

4

In [9]:
price[3]

5

In [10]:
food[3]

'Biryani'

In [11]:
price[0:]

array([5, 5, 5, 5])

In [12]:
food[0:]

array(['Pakora', 'Samosa', 'Raita', 'Biryani'], dtype='<U7')

In [13]:
food[1]

'Samosa'

In [14]:
price.mean()

5.0

In [15]:
# Zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
# Ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
#Range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#Specific range
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#Specific Interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#Table of five
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [21]:
#Linespace
np.linspace(1,100,num=10) #num is equal to that many numbers in that defined range 10 in our eg

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [22]:
# Specify your data type
np.ones(10,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [23]:
# Specify your data type
np.ones(10,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Arrays Functions

In [24]:
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [25]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [26]:
b=np.array([10.2,3.4,53.6,91.6])
b


array([10.2,  3.4, 53.6, 91.6])

In [27]:
c=np.concatenate((a,b))
c


array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6])

In [28]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  53.6,  91.6, 100. , 320. ])

# 2-D Arrays

In [29]:
a1=np.array([[1,2],[5,4]])
a1

array([[1, 2],
       [5, 4]])

In [30]:
b1=np.array([[6,7],[8,9]])
b1

array([[6, 7],
       [8, 9]])

In [31]:
c1=np.concatenate((a,b),axis=0) #To concatenate a 2D array dimmust be same 0 means 1st axis
c1

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6])

In [32]:
c1=np.concatenate((a1,b1),axis=1) # 1 means 2nd axis
c1

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [33]:
a2 = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
a2

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [34]:
#To find the number of dimensions
a2.ndim


3

In [35]:
b2=np.array([[5,6,7],
           [8,9,10],
           [11,12,13]])
b2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [36]:
b2.ndim

2

In [37]:
#Size (size=No. of elements)
a2.size

24

In [38]:
b2.size

9

In [39]:
#shape
a2.shape # (3,2,4) 3 is dim 2 is rows in each dim and 4 is columns in each dim 

(3, 2, 4)

In [40]:
#Reshape
a3=np.arange(12) #3*4
a3
a3.reshape(3,4) #Reshape product must be equal to number of elements of array like 3*4=12 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
#1D to 2D conversion
a4=np.array([1,2,3,4,5,6,7,8,9])
a4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a4.shape

(9,)

In [43]:
a4.ndim

1

In [44]:
#Rowwise
b4=a[np.newaxis, :]
b4

array([[  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
        320. ]])

In [45]:
b4.ndim

2

In [46]:
b4.shape

(1, 10)

In [47]:
#Columnwise
c4=a[: , np.newaxis]
c4

array([[  0.5],
       [  2. ],
       [  4. ],
       [  6. ],
       [ 10. ],
       [ 10.3],
       [ 12. ],
       [ 15. ],
       [100. ],
       [320. ]])

In [48]:
#Multiplying an array
a4*8

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72])

In [49]:
a4*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [50]:
#Adding
a4+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
#Subtracting
a4-6

array([-5, -4, -3, -2, -1,  0,  1,  2,  3])

In [52]:
a4.sum()

45

In [53]:
a4.mean()

5.0

In [54]:
#Reverse a 1D array
np.flip(a)

array([320. , 100. ,  15. ,  12. ,  10.3,  10. ,   6. ,   4. ,   2. ,
         0.5])