## 1-D Arrays

In [1]:
import numpy as np
a=np.array([1,414,409])
print(a)

[  1 414 409]


## 2-D Arrays

In [2]:
import numpy as np
b=np.array([[1,414,409],[1,414,409],[1,414,409]])
print(b)

[[  1 414 409]
 [  1 414 409]
 [  1 414 409]]


In [3]:
#Assembly line of a class is vector in numpy and assembly line of 10 classes is a matrix in numpy


In [4]:
#Array of zeros
a1=np.zeros(4)
a1

array([0., 0., 0., 0.])

In [5]:
#Array of ones
a2=np.ones(4)
a2

array([1., 1., 1., 1.])

In [6]:
a3=np.empty(4)
a3

array([1., 1., 1., 1.])

In [7]:
#Array with specific range
a4=np.arange(6)
a4

array([0, 1, 2, 3, 4, 5])

In [8]:
#Array with specific range
a5=np.arange(2,20)
a5

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [9]:
#Array with specific intervals
a6=np.arange(2,20,2)
a6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#Linearly spaced array
a7=np.linspace(0,10,num=5) #Same difference b/w all numbers
a7

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
#Linearly spaced array
a8=np.linspace(2,20,num=4)
a8

array([ 2.,  8., 14., 20.])

In [12]:
#Specific data type
import numpy as np
i=np.ones(5,dtype=np.int8)
i


array([1, 1, 1, 1, 1], dtype=int8)

In [13]:
import numpy as np
j=np.ones(5,dtype=np.float64)
j


array([1., 1., 1., 1., 1.])

In [14]:
import numpy as np
k=np.ones((5,6)) #Matrix
k


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## 3-D Array

In [16]:
c=np.arange(24).reshape(2,3,4) #2means 2 dim 3 means colums wise entries and 4 means row wise entries
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])